shared: &shared
    - Maid.Core/**
    - Maid.RabbitMQ/**
frontend:
    - UI/**
auth-api:
    - *shared
    - Maid.Auth.API/**
content-api:
    - *shared
    - Maid.Content/**
    - Maid.Notifications/**
    - Maid.Content.DB/**
    - Maid.Content.API/**
push-api:
    - *shared
    - Maid.Notifications/**
    - Maid.Notifications.DB/**
    - Maid.Notifications.API/**
quartz:
    - Maid.RabbitMQ/**
    - Maid.Quartz/**
