// <auto-generated />
using System;
using Maid.Manga.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Maid.Manga.DB.Migrations
{
    [DbContext(typeof(MangaDbContext))]
    [Migration("20190414192034_SourceFK4")]
    partial class SourceFK4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Maid.Manga.DB.MangaChapterInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Date");

                    b.Property<string>("Href");

                    b.Property<Guid?>("MangaId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("MangaId");

                    b.ToTable("MangaChapterInfo");
                });

            modelBuilder.Entity("Maid.Manga.DB.MangaInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Href");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Name");

                    b.Property<Guid?>("SourceId");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.ToTable("MangaInfo");
                });

            modelBuilder.Entity("Maid.Manga.DB.MangaSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("DomainUrl");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("MangaSource");

                    b.HasData(
                        new { Id = new Guid("41bd3be4-9e5d-4b9e-9709-11458285afb8"), CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Name = "FanFox" }
                    );
                });

            modelBuilder.Entity("Maid.Manga.DB.MangaChapterInfo", b =>
                {
                    b.HasOne("Maid.Manga.DB.MangaInfo", "Manga")
                        .WithMany("Chapters")
                        .HasForeignKey("MangaId");
                });

            modelBuilder.Entity("Maid.Manga.DB.MangaInfo", b =>
                {
                    b.HasOne("Maid.Manga.DB.MangaSource", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId");
                });
#pragma warning restore 612, 618
        }
    }
}
