name: Storage API build

on:
  push:
    branches: [ master ]
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      storage-api: ${{ steps.filter.outputs.storage-api }}
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: .github/filters.yaml
  docker:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.storage-api == 'true' }}
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./Maid.Storage.API/Dockerfile
          tags: maidadur/maid-storage-api:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  k8s:
    runs-on: ubuntu-latest
    needs: docker
    if: ${{ needs.changes.outputs.storage-api == 'true' }}
    steps:
      - 
        name: Set up kubectl
        uses: matootie/dokube@v1.3.4
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          clusterName: k8s-maid-cluster
      - 
        name: Delete pod
        run: kubectl delete pod -l app=maid-storage-api
